name: recraft
description: MC item recraft

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  
  # Architect
  mwwm: ^2.0.0
  relation: ^3.1.0

  # DI
  provider: ^6.0.0

  
  # util
  flutter_svg: ^1.0.3
  fake_async: ^1.2.0
  string_validator: ^0.3.0
  surf_util: ^1.0.3

  # network
  retrofit: ^2.0.1
  json_annotation: ^4.1.0
  dio: ^4.0.1

  # testing
  freezed_annotation: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  dart_code_metrics: ^4.2.1
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  freezed: ^0.15.1+1
  json_serializable: ^5.0.2
  retrofit_generator: ^2.0.1

  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
